on:
  push:
    branches:
    - main
  pull_request:

jobs:
  install_fdb:
    name: Install

    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install FoundationDB
        uses: ./

      - name: foundationdb status
        run: fdbcli --exec status
